#!/usr/bin/python3

import docker

client = docker.from_env()
mysql = client.containers.get('__mysql_container__')
drupal = client.containers.get('__drupal_container__')

print ('stoping mysql container...')
mysql.stop()

print ('stoping apache container...')
drupal.stop()
